### ISSUE TITLE
How i install the new ports collection to my miyoo mini with onion 4.0.2, if i have the few old ports?

### ISSUE THREAD

**Issue by RoGs7** [OnionUI/Ports-Collection#1]
i need a lot of help to install the ports collection, i having the few old ports...........i try to do it, it doesnt work at all, i think the installation or the file are not the same to put or are not the same installation before, i see retro breeze in youtube, he help me to install the old ports in my miyoo mini if that info contribuyes to give an example of tha files i use or tha files i have wich i use to play the few ports i have from the tutorial of retro breeze, by the way sorry my bad english........ill be greatfull if i get the help i need to play and install the new ports collection in my miyyo mini wiith onion 4.0.2.

**Comment by schmurtzm** [comment]
Hi, first read carefully the wiki about ports : 
https://github.com/OnionUI/Onion/wiki/Ports-Collection
(take an attentive look the the folder structure which has changed).

**What I recommend for the ports migration :**

 - Rename your old "Roms/PORTS" folder into something like Roms/PORTS_OLD
 - enable Ports Collection in PacMan app
 - Get the full port collection from here (first link in the readme):  https://github.com/OnionUI/Ports-Collection
 - Decompress the archive on your SD card
 - Then just fill the folders in Roms/PORTS/Games with your old assets
 - I have pre-configured many things, so during your copy past of assets do not override the existing files
 - Then run the ports import script 

The import script read the content of each shortcuts (.port and .notfound) files to find the field "GameDataFile".
GameDataFile="CP01.MAP" for example. If the file CP01.MAP exists in the Games directory  then the shortcut is renamed .port otherwise it will be .notfound

**Comment by RoGs7** [comment]
first of all, thank you a lot for some great info 4 me, second and i think last beacuse i understud generally all you said to me, when you say this in tha last point = * Then run the ports import script................. what you refeer???? to push tha home button of the mini and refresh roms???? or how i run tha ports import script????? i hope dont be bodering by tha way bro u.u .................. again thanks your help.

**Comment by schmurtzm** [comment]
No problem you're welcome :) 
In the ports rom list you should have "~Import ports" , run it to import all your ports.
If you don't have it uninstall and reinstall ports from Package Manager.

**Comment by RoGs7** [comment]
![IMG_20230331_120521](https://user-images.githubusercontent.com/106710461/229197527-0572bcb2-19ed-43a2-b08f-c0130f53787c.jpg)


LOOK BROTHER i dont have tha ~Import ports archive, i try tha reinstallation few times and nothing, i only have tha 2 files below down that are filter.miyoocmd and refresh roms.miyoocmd ..................i reallyyyyy want tha ports collection u.U..............i was thinking if you or someone can pass me tha link or in her tha file of "~Import ports".........i think i can get it if i only download tha file i try to get and put it into my miyoo and run it once i have generally all tha steps you tell me to do, I appreciate your help time u.u

**Comment by schmurtzm** [comment]
Please update your Onion with  last version ( currently 4.1.3, the script is included since 4.1.0).
Then apply my procedure again ;)
