### ISSUE TITLE
Wolfenstein 3D HD Mod

### ISSUE THREAD

**Issue by retropizza** [OnionUI/Ports-Collection#2]
Are you able to get the Wolfenstein HD mod working? I believe all the other ports are working for me, minus this one. The game starts up straight to the menu select screen and crashes with any button I press. 

I tested the setup on PC with ECWOLF.EXE and it worked, so I'm unsure what I'm missing.

BTW, thank you for all of your work on compiling these ports.

**Comment by schmurtzm** [comment]
Thank you :) 
It's already a victory if all other ports are working fine ;) 
I take a look tonight, indeed some users tell me that there are crash on wolfenstein HD, for now I don't know why ;)

**Comment by theVanZan** [comment]
Had the same problem myself. But I also noticed a problem with Blood and it's addon Cryptic Passage. I'll create a separate post for that.

**Comment by schmurtzm** [comment]
It comes from the core which crash due to audio sample that he don't like...
I have re-encoded the sound files in the mod pack with this little Windows batch : 

```
md out
for %%a in (*.wav) do (
  echo processing %%a
 ffmpeg -i "%%a" -acodec pcm_u8 -ac 1 -ar 11025 -filter:a "volume=0.5" "out\%%~na.wav" 
)
```
It doesn't crash anymore but the sound is saturated.
If you want to make a try the [modified mod file is here](https://www.dropbox.com/s/ne8q956ffqv7udv/wolf3d_hdpack.pk3).

**Comment by theVanZan** [comment]
Yeah it works now but the sound is poor unfortunately.

**Comment by schmurtzm** [comment]
As I can reproduce on PC, I've created this issue on the core repo : 
https://github.com/libretro/ecwolf/issues/93
